# Generated by Django 6.1.1 on 2026-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bmi_user_height_cm_user_pulse_bpm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
