# Generated by Django 6.1.1 on 2026-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medications_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appointment',
            name='supplies_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('MEDICATION', 'Medication'), ('CONSUMABLES', 'Consumables'), ('EQUIPMENT', 'Equipment'), ('GENERAL_ITEMS', 'General Items')], default='GENERAL_ITEMS', max_length=30),
        ),
    ]
