# Generated by Django 6.1.1 on 2026-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_archived',
            field=models.BooleanField(default=False),
        ),
    ]
